{{- if and .Values.keycloak.enabled .Values.keycloak.importRealm.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.keycloak.importRealm.configMapName | quote }}
data:
  {{ .Values.keycloak.importRealm.realmName }}-realm.json: |
    {
      "realm": "{{ .Values.keycloak.importRealm.realmName }}",
      "enabled": true,
      "clients": [
        {
          "clientId": "panel-frontend",
          "enabled": true,
          "publicClient": true,
          "redirectUris": ["*"],
          "defaultClientScopes": ["audience-panel-backend"]
        },
        {
          "clientId": "panel-backend",
          "enabled": true,
          "publicClient": false,
          "redirectUris": []
        }
      ],
      "clientScopes": [
        {
          "name": "audience-panel-backend",
          "protocol": "openid-connect",
          "protocolMappers": [
            {
              "name": "audience-mapper",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-mapper",
              "consentRequired": false,
              "config": {
                "included.client.audience": "panel-backend",
                "id.token.claim": "false",
                "access.token.claim": "true"
              }
            }
          ]
        }
      ]
    }
{{- end -}}
