{{- if not .Values.database.existingUserSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db.userSecretName" . }}
type: Opaque
data:
  username: {{ .Values.database.username | b64enc }}
  password: {{ .Values.database.password | b64enc }}
{{- end -}}
