{{- if .Values.ingress.enabled -}}
{{- $hostMatch := printf "Host(`%s`)" .Values.ingress.host -}}
{{- $authMatch := printf "%s && PathPrefix(`%s`)" $hostMatch .Values.provision.keycloak.publicPath -}}
{{- $fuegoMatch := printf "%s && PathPrefix(`/fhir`)" $hostMatch -}}
{{- $panelMatch := printf "%s && PathPrefix(`%s`)" $hostMatch .Values.provision.panel.publicPath -}}
{{- $name := .Release.Name -}}
{{- $httpRedirectMiddleware := printf "%s-http-redirect" $name -}}
{{- $rootRedirectMiddleware := printf "%s-root-redirect" $name -}}
{{- $tlsSecretName := printf "%s-tls" $name -}}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $name }}
spec:
  commonName: {{ .Values.ingress.host | quote }}
  secretName: {{ $tlsSecretName }}
  dnsNames:
    - {{ .Values.ingress.host | quote }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $httpRedirectMiddleware }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $rootRedirectMiddleware }}
spec:
  redirectRegex:
    regex: ^https?://([^/]+)/(?:\?.*)?$
    replacement: https://${1}
      {{- if .Values.provision.panel.enabled -}}
        {{ .Values.provision.panel.publicPath }}
      {{- else -}}
        {{ .Values.provision.keycloak.publicPath }}
      {{- end }}
    permanent: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $name }}-web
spec:
  entryPoints: [web]
  routes:
    - match: {{ $hostMatch }}
      kind: Rule
      middlewares:
        - name: {{ $httpRedirectMiddleware }}
      services:
        - name: noop@internal
          kind: TraefikService
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $name }}-websecure
spec:
  entryPoints: [websecure]
  tls:
    secretName: {{ $tlsSecretName }}
  routes:
    {{- if .Values.provision.keycloak.enabled }}
    - match: {{ $authMatch }}
      kind: Rule
      services:
        - name: {{ .Release.Name }}-keycloak
          port: http
    {{- end }}
    {{- if .Values.provision.fuego.enabled }}
    - match: {{ $fuegoMatch }}
      kind: Rule
      services:
        - name: {{ include "fuego.svcName" . }}
          port: http
    {{- end }}
    {{- if .Values.provision.panel.enabled }}
    - match: {{ $panelMatch }}
      kind: Rule
      services:
        - name: {{ include "panel.svcName" . }}
          port: http
    {{- end }}
    {{- if or .Values.provision.panel.enabled .Values.provision.keycloak.enabled }}
    - match: {{ $hostMatch }}
      kind: Rule
      middlewares:
        - name: {{ $rootRedirectMiddleware }}
      services:
        - name: noop@internal
          kind: TraefikService
    {{- end }}
{{- end -}}
