registryAuth:
  enabled: false
  server: "repo.firemetricshealth.com"
  username: ""
  password: ""

ingress:
  enabled: false
  host: ""

database:
  dbname: firemetrics
  username: postgres
  password: postgres
  port: 5432
  # externalHostname is only used if provisioning of Spilo is disabled.
  externalHostname: ""

oidc:
  enabled: true
  # externalDiscoveryUrl is only used if provisioning of Keycloak, realm or ingress is disabled.
  externalDiscoveryUrl: ""

fuego:
  # externalUrl is only used if provisioning of Fuego or ingress is disabled.
  externalUrl: ""

panel:
  enabled: true
  # externalUrl is only used if provisioning of Panel or ingress is disabled.
  externalUrl: ""
  oidc:
    clientId: "panel"
    # audience is optional. If not set, it will default to the Panel's public URL.
    audience: ""

provision:
  keycloak:
    enabled: true
    publicPath: /auth
    importRealm:
      enabled: true
      configMapName: keycloak-import
      realmName: firemetrics
    persistence:
      enabled: true
      claimName: keycloak-data
      size: 1Gi
  panel:
    enabled: true
    image: repo.firemetricshealth.com/ghcr/firemetrics/fmx-panel:2b36a31
    publicPath: "/panel"
    datasetImportDisabled: false
  fuego:
    enabled: true
    image: repo.firemetricshealth.com/ghcr/firemetrics/fuego:aa1f58e2
  spilo:
    enabled: true
    image: repo.firemetricshealth.com/ghcr/firemetrics/spilo16:3.3-p2-latest
    requestedStorage: 10Gi
    tolerateLowMemory: true

keycloak:
  production: true
  httpRelativePath: /auth/
  proxyHeaders: xforwarded
  extraStartupArgs: "--import-realm"
  externalDatabase:
    host: "none"
  extraVolumes:
    - name: keycloak-data
      persistentVolumeClaim:
        claimName: keycloak-data
    - name: keycloak-import
      configMap:
        name: keycloak-import
  extraVolumeMounts:
    - name: keycloak-data
      mountPath: /opt/bitnami/keycloak/data/h2
    - name: keycloak-import
      mountPath: /opt/bitnami/keycloak/data/import
  postgresql:
    enabled: false
  extraEnvVars:
    - name: KEYCLOAK_DATABASE_VENDOR
      value: "dev-file"
  externalDatabase:
    password: notused
