registryAuth:
  enabled: false
  server: "repo.firemetricshealth.com"
  username: ""
  password: ""

db:
  image: repo.firemetricshealth.com/ghcr/firemetrics/spilo16:3.3-p2-latest
  pg:
    dbname: firemetrics
    user: postgres
    password: postgres
  requestedStorage: 10Gi

ingress:
  enabled: false
  host: ""

panel:
  enabled: true
  image: repo.firemetricshealth.com/ghcr/firemetrics/fmx-panel:956c5c0
  oidc:
    discoveryUrl: ""
    clientId: "panel-backend"
    frontendClientId: "panel-frontend"

keycloak:
  enabled: true

  importRealm:
    enabled: true
    configMapName: keycloak-import
    realmName: firemetrics

  persistence:
    enabled: true
    claimName: keycloak-data
    size: 1Gi

  production: true
  httpRelativePath: /auth/
  proxyHeaders: xforwarded
  extraStartupArgs: "--import-realm"
  externalDatabase:
    host: "none"
  extraVolumes:
    - name: keycloak-data
      persistentVolumeClaim:
        claimName: keycloak-data
    - name: keycloak-import
      configMap:
        name: keycloak-import
  extraVolumeMounts:
    - name: keycloak-data
      mountPath: /opt/bitnami/keycloak/data/h2
    - name: keycloak-import
      mountPath: /opt/bitnami/keycloak/data/import
  postgresql:
    enabled: false
  extraEnvVars:
    - name: KEYCLOAK_DATABASE_VENDOR
      value: "dev-file"
  externalDatabase:
    password: notused
