{
 "title": "FHIR Numbers",
 "tags": [ "firemetrics-dev" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "resources",
    "query": "select \n  table_name \nfrom \n  information_schema.tables \nwhere \n  table_schema = current_schema() and  \n  table_name !~ '_'\norder by 1\n"
   },
   {
    "name": "identifiers",
    "query": "SELECT \n  SUBSTRING(table_name FROM '(.+)_identifier') AS base_name\nFROM \n  information_schema.tables \nWHERE \n  table_schema = current_schema() \n  AND \n  table_name LIKE '${resources}%_identifier'\norder by 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Number of FHIR Resources",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n   sum(resource_count) \"Number of Resources\"\nFROM \n  fm_resource_counts"
    }
   ]
  },
  {
   "title": "Last Resource Updates",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select \n  resource_name \"Resource Name\", \n  last_updated \"Last Updated\"\nfrom fm_get_last_resource_updates() order by 2 desc nulls last;"
    }
   ]
  },
  {
   "title": "Resource Counts",
   "type": "barchart",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n   resource_name \"Resource Name\",\n   resource_count \"Number of Resources\"\nFROM \n  fm_resource_counts\nORDER BY 2 desc;\n"
    }
   ]
  },
  {
   "title": "${identifiers}",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "select fmx_code(system) \"system\" from \"${identifiers}_identifier\" group by system order by 1"
    }
   ]
  },
  {
   "title": "${resources} distribution",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 16, "x": 8, "y": 32 },
   "targets": [
    {
     "rawSql": "select \n  count(*) \"count\",\n  fmx_code(i.system) \"system\"\nfrom \n  ${resources} r\n  join ${resources}_identifier i on r._id = i._resource \ngroup by i.system\norder by count(*) desc"
    }
   ]
  }
 ]
}