{
 "title": "Hospital Control Center",
 "tags": [ "firemetrics-dev" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of Patients",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct p0.id) as \"Number of Patients\"\nFROM\n  patient p0;"
    }
   ]
  },
  {
   "title": "Average Patient Age at Admission",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH latest_encounter AS (\n  SELECT\n    es0._reference_id AS patient_id,\n    MAX(lower(ep0.start)) AS latest_encounter_start,\n    lower(p1.\"birthDate\") AS birth_date\n  FROM\n    encounter e0\n    JOIN encounter_period ep0 ON ep0._resource = e0._id\n    JOIN encounter_subject es0 ON es0._resource = e0._id\n    JOIN patient p1 ON (\n      p1._id = es0._reference_id\n      AND es0._reference_type = 'Patient'\n    )\n  GROUP BY\n    es0._reference_id, p1.\"birthDate\"\n)\nSELECT\n  AVG(EXTRACT(YEAR FROM AGE(latest_encounter_start, birth_date))) AS \"average_age\"\nFROM\n  latest_encounter;\n"
    }
   ]
  },
  {
   "title": "Vital Status",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    WHEN p0.\"deceasedDateTime\" IS NOT NULL THEN 'deceased'\n    ELSE 'alive'\n  END AS \"status\",\n  COUNT(*) AS \"count\"\nFROM\n  patient p0\nGROUP BY\n  CASE\n    WHEN p0.\"deceasedDateTime\" IS NOT NULL THEN 'deceased'\n    ELSE 'alive'\n  END;\n"
    }
   ]
  },
  {
   "title": "Admission Type",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  fmx_code (ec0.code) \"ec0_code\",\n  COUNT(*) AS \"stay_type\"\nFROM\n  encounter e0\n  JOIN encounter_class ec0 ON (ec0._resource = e0._id)\nGROUP BY\n  \"ec0_code\"\nORDER BY \n  \"ec0_code\" ASC"
    }
   ]
  },
  {
   "title": "Insurance Types",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  ci.display,\n  count(ci.display) \"Counts\"\nFROM\n  claim c\n  JOIN claim_insurance_coverage ci on c._id = ci._resource\nGROUP BY\n  ci.display\nORDER BY\n  \"Counts\" DESC;\n"
    }
   ]
  },
  {
   "title": "Patient List",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n  pn0.family \"Family Name\",\n  png0.value \"First Name\",\n  fmx_code (p0.gender) \"Gender\",\n  lower(p0.\"birthDate\") \"Birth Date\",\n  CASE\n    WHEN p0.\"deceasedDateTime\" IS NOT NULL THEN 'deceased'\n    ELSE 'alive'\n  END AS \"Vital Status\",\n  pmc0.display \"Marital Status\",\n  lower(p0.\"deceasedDateTime\") \"Deceased Date\",\n  p0.id as \"Individual Patient Link\"\nFROM\n  patient p0\n  JOIN patient_name pn0 ON (pn0._resource = p0._id)\n  JOIN patient_name_given png0 ON (png0._resource = p0._id)\n  JOIN \"patient_maritalStatus\" pm0 ON (pm0._resource = p0._id)\n  JOIN \"patient_maritalStatus_coding\" pmc0 ON (pmc0._resource = p0._id);"
    }
   ]
  },
  {
   "title": "Total Encounters over Years",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  MAKE_DATE(EXTRACT(YEAR FROM lower(ep0.start))::int, 1, 1) AS \"encounter_year\",\n  COUNT(*) AS \"number_of_claims\"\nFROM\n  encounter e0\n  JOIN encounter_period ep0 ON ep0._resource = e0._id\nGROUP BY\n  EXTRACT(YEAR FROM lower(ep0.start))\n"
    }
   ]
  },
  {
   "title": "Encounter Stay Categories (in Hours)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    WHEN EXTRACT(EPOCH FROM (lower(ep0.end) - lower(ep0.start))) / 60 / 60 < 1 THEN 'Less than 1 hour'\n    WHEN EXTRACT(EPOCH FROM (lower(ep0.end) - lower(ep0.start))) / 60 / 60 >= 1 AND EXTRACT(EPOCH FROM (lower(ep0.end) - lower(ep0.start))) / 60 / 60 < 3 THEN 'More than 1 hour and less than 3 hours'\n    WHEN EXTRACT(EPOCH FROM (lower(ep0.end) - lower(ep0.start))) / 60 / 60 >= 3 THEN 'More than 3 hours'\n  END AS \"stay_duration_group\",\n  COUNT(*) AS \"total_count\"\nFROM\n  encounter e0\n  JOIN encounter_period ep0 ON ep0._resource = e0._id\nGROUP BY\n  CASE\n    WHEN EXTRACT(EPOCH FROM (lower(ep0.end) - lower(ep0.start))) / 60 / 60 < 1 THEN 'Less than 1 hour'\n    WHEN EXTRACT(EPOCH FROM (lower(ep0.end) - lower(ep0.start))) / 60 / 60 >= 1 AND EXTRACT(EPOCH FROM (lower(ep0.end) - lower(ep0.start))) / 60 / 60 < 3 THEN 'More than 1 hour and less than 3 hours'\n    WHEN EXTRACT(EPOCH FROM (lower(ep0.end) - lower(ep0.start))) / 60 / 60 >= 3 THEN 'More than 3 hours'\n  END\nORDER BY\n  \"total_count\" DESC;\n"
    }
   ]
  }
 ]
}