{
 "title": "Patient Cohort Analysis",
 "tags": [ "firemetrics-dev" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "conditions",
    "label": "Conditions",
    "query": "select ccc.display value from condition_code_coding ccc"
   }
  ]
 },
 "panels": [
  {
   "title": "General Stats",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "with cohort as (\n  select \n    lower(p.\"birthDate\") birthdate,\n    lower(p.\"deceasedDateTime\") deceased_date,\n    fmx_code(p.gender) gender,\n    age(coalesce(lower(p.\"deceasedDateTime\"), now()), lower(p.\"birthDate\")) as age\n  from patient p\n  where exists (\n    select true from condition_code_coding ccc \n    join condition_subject cs on (ccc._resource = cs._resource and ccc.display in (${conditions}) and p._id = cs._reference_id and cs._reference_type = 'Patient')\n  )\n) select\n  count(*) \"Cohort Size\",\n    extract(year from avg(age)) \"Average age\",\n    extract(year from percentile_cont(0.5) within group (order by age)) \"Median Age\",\n    date_trunc('day', min(cohort.age)) \"Youngest age\",\n    max(cohort.birthdate)::text \"Youngest birthdate\",\n    date_trunc('day', max(cohort.age)) \"Oldest age\",\n    min(cohort.birthdate)::text \"Oldest birthdate\"\n  from cohort "
    }
   ]
  },
  {
   "title": "Age Distribution",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select \n\textract(year from age(coalesce(lower(p.\"deceasedDateTime\"), now()), lower(p.\"birthDate\"))) as age\nfrom patient p\nwhere exists (\n  select true from condition_code_coding ccc \n  join condition_subject cs on (ccc._resource = cs._resource and ccc.display in (${conditions}) and p._id = cs._reference_id and cs._reference_type = 'Patient')\n)"
    }
   ]
  },
  {
   "title": "Languages",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select \n  coalesce(pcl.text, 'unknown') lang,\n  count(*) \"count\" \nfrom patient_communication_language pcl \nwhere exists (\n  select true from condition_code_coding ccc \n  join condition_subject cs on (ccc._resource = cs._resource and ccc.display in (${conditions}) and pcl._resource = cs._reference_id and cs._reference_type = 'Patient')\n)\ngroup by pcl.text \norder by count(*) desc"
    }
   ]
  },
  {
   "title": "Where the Patients Are From",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select\n  jsonb_path_query_first(pa.extension, '$[*] ? (@.url == \"http://hl7.org/fhir/StructureDefinition/geolocation\").extension ? (@[*].url == \"latitude\").valueDecimal')::numeric latitude,\n  jsonb_path_query_first(pa.extension, '$[*] ? (@.url == \"http://hl7.org/fhir/StructureDefinition/geolocation\").extension ? (@[*].url == \"longitude\").valueDecimal')::numeric longitude\nfrom patient_address pa\nwhere exists (\n  select true from condition_code_coding ccc \n  join condition_subject cs on (ccc._resource = cs._resource and ccc.display in (${conditions}) and pa._resource = cs._reference_id and cs._reference_type = 'Patient')\n)"
    }
   ]
  },
  {
   "title": "Gender Distribution",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  fmx_code(p.gender) gender,\n  count(*) \nfrom patient p\nwhere exists (\n  select true from condition_code_coding ccc \n  join condition_subject cs on (ccc._resource = cs._resource and ccc.display in (${conditions}) and p._id = cs._reference_id and cs._reference_type = 'Patient')\n)\ngroup by p.gender \norder by count(*) desc"
    }
   ]
  },
  {
   "title": "Marital Status",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  case \n    when fmx_code(pm.code) = 'M' then 'Married'\n    when fmx_code(pm.code) = 'S' then 'Never Married'\n    else fmx_code(pm.code)\n  end \"Marital Status\",\n  count(*) \"count\" \nfrom \"patient_maritalStatus_coding\" pm \nwhere exists (\n  select true from condition_code_coding ccc \n  join condition_subject cs on (ccc._resource = cs._resource and ccc.display in (${conditions}) and pm._id = cs._reference_id and cs._reference_type = 'Patient')\n)\ngroup by pm.code \norder by count(*) desc"
    }
   ]
  }
 ]
}