{
 "title": "Claim Control Center",
 "tags": [ "firemetrics-dev" ],
 "time": { "from": "1992-01-01T00:00:00.000Z", "to": "2021-01-01T00:00:00.000Z" },
 "panels": [
  {
   "title": "Total # Number of Claims",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(c0.id) \"c0_id\"\nFROM\n  claim c0;"
    }
   ]
  },
  {
   "title": "Top 15 Reasons Claimed (Total)",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  cipc0.display AS \"cipc0_display\",\n  SUM(cin0.value) AS \"total_value\",\n  fmx_code(cin0.currency) AS \"cin0_currency\"\nFROM\n  claim c0\n  JOIN claim_item ci0 ON ci0._resource = c0._id\n  JOIN \"claim_item_productOrService\" cip0 ON cip0._resource = ci0._id\n  JOIN \"claim_item_productOrService_coding\" cipc0 ON cipc0._resource = ci0._id\n  JOIN claim_item_net cin0 ON cin0._resource = ci0._id\nGROUP BY\n  cipc0.display, cin0.currency\nORDER BY\n  \"total_value\" DESC\nLIMIT 15;\n"
    }
   ]
  },
  {
   "title": "Top 10 Claims",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  c0.id \"c0_id\",\n  ct0.value \"ct0_value\",\n  fmx_code (ct0.currency) \"ct0_currency\"\nFROM\n  claim c0\n  JOIN claim_total ct0 ON (ct0._resource = c0._id)\nORDER BY\n  ct0.value DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top Encounter Reasons",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  cipc0.display AS \"cipc0_display\",\n  COUNT(*) AS \"display_count\"\nFROM\n  claim c0\n  JOIN claim_item ci0 ON ci0._resource = c0._id\n  JOIN \"claim_item_productOrService\" cip0 ON cip0._resource = ci0._id\n  JOIN \"claim_item_productOrService_coding\" cipc0 ON cipc0._resource = ci0._id\nGROUP BY\n  cipc0.display\nORDER BY\n  \"display_count\" DESC\nLIMIT 15;\n"
    }
   ]
  },
  {
   "title": "Total $ Claims over Years",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n  MAKE_DATE(EXTRACT(YEAR FROM lower(c0.created))::int, 1, 1) AS \"claim_year\",\n  SUM(ct0.value) AS \"total_sum\"\nFROM\n  claim c0\n  JOIN claim_total ct0 ON ct0._resource = c0._id\nGROUP BY\n  EXTRACT(YEAR FROM lower(c0.created))\nORDER BY\n  \"claim_year\" DESC\nLIMIT 30;\n"
    }
   ]
  },
  {
   "title": "# of Claims per Year",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  MAKE_DATE(EXTRACT(YEAR FROM lower(c0.created))::int, 1, 1) AS \"claim_year\",\n  COUNT(*) AS \"number_of_claims\"\nFROM\n  claim c0\nGROUP BY\n  EXTRACT(YEAR FROM lower(c0.created))\nORDER BY\n  \"claim_year\" DESC\nLIMIT 30;\n"
    }
   ]
  }
 ]
}