{
 "title": "DICOM Receiver",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Latest studies",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select \n  start_datetime,\n  end_datetime,\n  EXTRACT(EPOCH FROM (end_datetime - start_datetime)) duration,\n  accession_number,\n  coalesce(di.tags->'00081032'->'Value'->0->'00080100'->'Value'->>0, 'Unknown') procedure_code,\n  coalesce(dicom.get_tag(di.tags,'Modality'), 'Unknown') modality,\n  coalesce(study_description, 'Unknown') study_description,\n  coalesce(dicom.get_tag(di.tags,'BodyPartExamined'), 'Unknown') body_part,\n  coalesce(dicom.get_tag(di.tags,'StationName'), 'Unknown') station_name,\n  coalesce(dicom.get_tag(di.tags,'ManufacturerModelName'), 'Unknown') model_name,\n  coalesce(dicom.get_tag(di.tags,'InstitutionName'), 'Unknown') institution_name,\n  coalesce(dicom.get_tag(di.tags, 'RequestingService'), 'Unknown') requesting_service,\n  num_instances\nFROM dicom.dicom_studies ds\nLEFT JOIN LATERAL (\n  SELECT tags\n  FROM dicom.dicom_instances di\n  WHERE \n    di.study_instance_uid = ds.study_instance_uid AND \n    dicom.get_tags(tags, 'ImageType') @> ARRAY['ORIGINAL', 'PRIMARY']\n  ORDER BY di.sop_instance_uid asc\n  LIMIT 1\n) di ON TRUE\nwhere \n  ds.start_datetime is not null and \n  ds.start_datetime >= $__timeFrom() and ds.start_datetime <= $__timeTo()\norder by ds.start_datetime desc"
    }
   ]
  },
  {
   "title": "FHIRization Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select \n  count(ds.study_instance_uid) \"DICOM\",\n  count(isi.value) \"FHIR\",\n  ds.start_datetime::date study_date\nfrom dicom.dicom_studies ds\nleft join imagingstudy_identifier isi on isi.value = ds.study_urn_oid and isi.system = fmx_read_code('urn:dicom:uid')\nwhere \n  ds.start_datetime is not null and \n  ds.start_datetime >= $__timeFrom() and ds.start_datetime <= $__timeTo()\ngroup by ds.start_datetime::date\norder by ds.start_datetime::date"
    }
   ]
  },
  {
   "title": "Last DICOM->FHIR Processing",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 9 },
   "targets": [
    {
     "rawSql": "select \n  (value->>'last_run_ts')::timestamp\nfrom dicom.state\nwhere key = 'dicom_to_fhir_delta_key'\nlimit 1;"
    }
   ]
  },
  {
   "title": "Mean Duration [minutes]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Mean Duration [minutes]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Procedure Code",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Study Description",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Body Parts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Requesting Service",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Station Name",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Institution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Modality",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 5 }
   ]
  }
 ]
}