{
 "title": "Patient-Dashboard",
 "tags": [ "firemetrics-dev" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pat",
    "query": "SELECT p.id FROM patient p JOIN patient_name pn on p._id = pn._resource"
   }
  ]
 },
 "panels": [
  {
   "title": "Patient Details",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  pnf.value || ' ' || pn.family || ', ' || png.value \"Name\",\n  lower(p.\"birthDate\") || ' (' || DATE_PART('YEAR', AGE(NOW(), lower(p.\"birthDate\"))) || 'Y)' \"Birthdate\",\n  fmx_code(p.gender) \"Gender\",\n  pmc.display \"Marital Status\",\n    CASE\n    WHEN p.\"deceasedDateTime\" IS NOT NULL THEN '✝ ' || lower(p.\"deceasedDateTime\")\n    ELSE '-'\n  END AS deceased\nFROM\n  patient p\n  JOIN patient_name pn on p._id = pn._resource\n  JOIN patient_name_given png on p._id = png._resource\n  JOIN patient_name_prefix pnf on p._id = pnf._resource\n  JOIN \"patient_maritalStatus_coding\" pmc ON (pmc._resource = p._id)\nWHERE\n  p.id = '${pat}'"
    }
   ]
  },
  {
   "title": "Encounter Overview",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.id,\n  lower(ep.start) \"start\",\n  lower(ep.end) \"end\",\n  EXTRACT(EPOCH FROM (lower(ep.end) - lower(ep.start))) / 60 / 60 \"Stay Duration\"\nFROM\n  encounter e\n  JOIN encounter_period ep on e._id = ep._resource\n  JOIN encounter_subject es on e._id = es._resource\n  JOIN patient p on (es._reference_id = p._id AND es._reference_type = 'Patient')\nWHERE p.id = '${pat}'"
    }
   ]
  },
  {
   "title": "Immunization",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  lower(i0.\"occurrenceDateTime\") \"Date\",\n  fmx_code (i0.status) \"Status\" ,\n  fmx_code (ivc0.code) \"Code\",\n  iv0.text \"Description\"\nFROM\n  immunization i0\n  JOIN \"immunization_vaccineCode\" iv0 ON (iv0._resource = i0._id)\n  JOIN \"immunization_vaccineCode_coding\" ivc0 ON (ivc0._resource = i0._id)\n  JOIN immunization_patient ip0 ON (ip0._resource = i0._id)\n  JOIN patient p1 ON (\n    p1._id = ip0._reference_id\n    and ip0._reference_type = 'Patient'\n  )\nWHERE\n  p1.id = '${pat}';"
    }
   ]
  },
  {
   "title": "Side Information",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  lower(o0.\"effectiveDateTime\") \"Date\",\n  fmx_code (o0.status) \"Status\",\n  fmx_code (ovc0.code) \"Code\",\n  ovc0.display \"Display\"\nFROM\n  observation o0\n  JOIN \"observation_valueCodeableConcept\" ov0 ON (ov0._resource = o0._id)\n  JOIN \"observation_valueCodeableConcept_coding\" ovc0 ON (ovc0._resource = o0._id)\n  JOIN observation_subject os0 ON (os0._resource = o0._id)\n  JOIN patient p1 ON (\n    p1._id = os0._reference_id\n    AND os0._reference_type = 'Patient'\n  )\nWHERE\n  p1.id = '${pat}'\nORDER BY\n  \"Date\" DESC;"
    }
   ]
  },
  {
   "title": "Laboratory Values",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  lower(o0.\"effectiveDateTime\") \"Date\",\n  occ.display \"Measurement\",\n  round(ov0.value, 2) || fmx_code (ov0.code) \"Value\",\n  ov0.unit \"Unit\"\nFROM\n  observation o0\n  JOIN \"observation_valueQuantity\" ov0 ON (ov0._resource = o0._id)\n  JOIN observation_subject os0 ON (os0._resource = o0._id)\n  JOIN observation_code_coding occ on (occ._resource = o0._id)\n  LEFT JOIN \"observation_referenceRange_low\" orl on (orl._resource = o0._id)\n  JOIN patient p1 ON (\n    p1._id = os0._reference_id\n    and os0._reference_type = 'Patient'\n  )\nWHERE\n  p1.id = '${pat}'\nORDER BY\n  \"Date\" DESC;"
    }
   ]
  },
  {
   "title": "Procedures",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  lower(ppp.start) \"Start\",\n  lower(ppp.end) \"End\",\n  fmx_code (p0.status) \"Status\",\n  fmx_code (pcc0.code) \"Code\",\n  pcc0.display \"Description\"\nFROM\n  procedure p0\n  JOIN procedure_code pc0 ON (pc0._resource = p0._id)\n  JOIN procedure_code_coding pcc0 ON (pcc0._resource = p0._id)\n  JOIN procedure_subject ps0 ON (ps0._resource = p0._id)\n  JOIN \"procedure_performedPeriod\" ppp on p0._id = ppp._resource\n  JOIN patient p1 ON (\n    p1._id = ps0._reference_id\n    and ps0._reference_type = 'Patient'\n  )\nWHERE\n  p1.id = '${pat}'"
    }
   ]
  },
  {
   "title": "Medication Requests",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\n  lower(m0.\"authoredOn\") \"Created\",\n  mmc0.display \"Description\",\n  fmx_code (mmc0.code) \"Code\",\n  fmx_code (m0.status) \"Statsu\"\nFROM\n  medicationrequest m0\n  JOIN \"medicationrequest_medicationCodeableConcept\" mm0 ON (mm0._resource = m0._id)\n  JOIN \"medicationrequest_medicationCodeableConcept_coding\" mmc0 ON (mmc0._resource = m0._id)\n  JOIN medicationrequest_subject ms0 ON (ms0._resource = m0._id)\n  JOIN patient p1 ON (\n    p1._id = ms0._reference_id\n    and ms0._reference_type = 'Patient'\n  )\nWHERE \n  p1.id = '${pat}';"
    }
   ]
  }
 ]
}