{{ if .Values.provision.spilo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spilo.svcName" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.port }}
      targetPort: tcp
  selector:
    app.kubernetes.io/part-of: {{ include "appName" . }}
    app.kubernetes.io/component: database
    app.kubernetes.io/name: {{ include "spilo.podLabel" . }}
{{- end }}
