{{- $caCertsVolumeName := "ca-certs" -}}
{{- $caCertsPath := printf "/etc/ssl/certs/%s" .Values.caCertsConfigMap.fileName -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{ include "appName" . }}
      app.kubernetes.io/component: backend
      app.kubernetes.io/name: {{ include "podLabel" . }}
  template:
    metadata:
      name: {{ include "appName" . }}
      labels:
        app.kubernetes.io/part-of: {{ include "appName" . }}
        app.kubernetes.io/component: backend
        app.kubernetes.io/name: {{ include "podLabel" . }}
    spec:
      {{- with .Values.serviceAccountName }}
      serviceAccountName: {{ . }}
      {{- end }}

      {{- with .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}

      {{- if or .Values.caCertsConfigMap.enabled .Values.volumes }}
      volumes:
        - name: {{ $caCertsVolumeName }}
          configMap:
            defaultMode: 0644
            name: {{ .Values.caCertsConfigMap.name | quote }}

        {{- with .Values.volumes }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
      {{- end }}

      {{- if or .Values.bootstrapKeycloak.enabled .Values.initContainers }}
      initContainers:

        {{- if .Values.bootstrapKeycloak.enabled }}
        - name: bootstrap-keycloak
          image: {{ .Values.bootstrapKeycloak.image | quote }}
          env:
            - name: KEYCLOAK_URL
              value: {{ .Values.bootstrapKeycloak.url | quote }}
            - name: KEYCLOAK_REALM
              value: {{ .Values.bootstrapKeycloak.realm | quote }}
            - name: KEYCLOAK_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bootstrapKeycloak.adminUserSecret.name | quote }}
                  key: {{ .Values.bootstrapKeycloak.adminUserSecret.usernameKey | quote }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bootstrapKeycloak.adminUserSecret.name | quote }}
                  key: {{ .Values.bootstrapKeycloak.adminUserSecret.passwordKey | quote }}
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "oidcClientSecretName" . | quote }}
                  key: {{ .Values.oidc.clientSecret.idKey | quote }}
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "oidcClientSecretName" . | quote }}
                  key: {{ .Values.oidc.clientSecret.secretKey | quote }}
          command:
            - sh
            - -c
            - |
              set -euo pipefail

              echo "Fetching admin token..."
              TOKEN=$(curl -sS -X POST \
                -d "client_id=admin-cli" \
                -d "username=$KEYCLOAK_ADMIN_USERNAME" \
                -d "password=$KEYCLOAK_ADMIN_PASSWORD" \
                -d "grant_type=password" \
                "$KEYCLOAK_URL/realms/master/protocol/openid-connect/token" \
                | sed -n 's/.*"access_token":"\([^"]*\)".*/\1/p')

              if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
                echo "Failed to obtain admin token"
                exit 1
              fi

              STATUS=$(curl -sS -o /dev/null -w "%{http_code}" \
                -X POST "$KEYCLOAK_URL/admin/realms/$KEYCLOAK_REALM/clients" \
                -H "Authorization: Bearer $TOKEN" \
                -H "Content-Type: application/json" \
                -d '{
                  "clientId": "'$CLIENT_ID'",
                  "secret": "'$CLIENT_SECRET'",
                  "enabled": true,
                  "publicClient": false,
                  "serviceAccountsEnabled": true,
                  "directAccessGrantsEnabled": false,
                  "standardFlowEnabled": false,
                  "authorizationServicesEnabled": false
                }')

              if [ "$STATUS" -eq 201 ]; then
                echo "Client created successfully."
              elif [ "$STATUS" -eq 409 ]; then
                echo "Client already exists, continuing..."
              else
                echo "Failed to create client (HTTP $STATUS)"
                exit 1
              fi
        {{- end }}

        {{- with .Values.initContainers }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
      {{- end }}

      containers:
        - name: main
          image: {{ .Values.image | quote }}
          {{- with .Values.securityContext }}
          securityContext: {{- . | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000

          {{- if or .Values.caCertsConfigMap.enabled .Values.volumeMounts }}
          volumeMounts:
            - name: {{ $caCertsVolumeName }}
              mountPath: {{ $caCertsPath }}
              readOnly: true
              subPath: {{ .Values.caCertsConfigMap.fileName | quote }}

            {{- with .Values.volumeMounts }}
              {{- . | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}

          env:
            - name: FUEGO_SERVER_INTERFACE
              value: "0.0.0.0"
            - name: FUEGO_SERVER_PORT
              value: "3000"
            - name: FUEGO_SERVER_PUBLIC_URL
              value: {{ .Values.publicUrl | quote }}
            - name: FUEGO_DATABASE_HOST
              value: {{ .Values.database.hostname | quote }}
            - name: FUEGO_DATABASE_PORT
              value: {{ .Values.database.port | quote }}
            - name: FUEGO_DATABASE_DBNAME
              value: {{ .Values.database.dbname | quote }}
            - name: FUEGO_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.userSecret | quote }}
                  key: username
            - name: FUEGO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.userSecret | quote }}
                  key: password

            {{- if .Values.oidc.enabled }}
            - name: FUEGO_OIDC_ENABLE
              value: "true"
            - name: FUEGO_OIDC_DISCOVERY_URL
              value: {{ .Values.oidc.discoveryUrl | quote }}
            - name: FUEGO_OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "oidcClientSecretName" . | quote }}
                  key: {{ .Values.oidc.clientSecret.idKey | quote }}
            - name: FUEGO_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "oidcClientSecretName" . | quote }}
                  key: {{ .Values.oidc.clientSecret.secretKey | quote }}
            {{- end }}

            {{- with .Values.env }}
              {{- . | toYaml | nindent 12 }}
            {{- end }}
