{{- if and .Values.hapi.enabled .Values.hapi.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hapiSvcName" . }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/part-of: {{ include "appName" . }}
    app.kubernetes.io/component: hapi
    app.kubernetes.io/name: {{ include "hapiPodLabel" . }}
{{- end -}}