serviceAccountName: ""
imagePullSecret: ""
securityContext: {}

receiver:
  # -- Enable the DICOM receiver component.
  enabled: true
  # -- The image used for the DICOM receiver.
  image: ghcr.io/firemetrics/dicom_receiver:f489565f
  # -- Extra init containers for the DICOM receiver.
  initContainers: []
  # -- Extra environment variables for the DICOM receiver.
  env: []
  # -- Extra volumes for the DICOM receiver.
  volumes: []
  # -- Extra volume mounts for the DICOM receiver.
  volumeMounts: []
  service:
    # -- The service type for the DICOM receiver. Use "NodePort" to expose on the node.
    type: NodePort
    # -- The node port for the DICOM receiver service (optional, only used when type is NodePort).
    nodePort: ""
  dicom:
    # -- The log level for the DICOM receiver.
    logLevel: INFO
    # -- The port for the DICOM receiver.
    port: 11112
    # -- The Application Entity Title (AET) for the DICOM receiver.
    aet: FMX
    # -- The number of worker threads for the DICOM receiver.
    numThreads: 8
  database:
    hostname: postgres
    dbname: postgres
    schema: dicom
    port: 5432
    userSecret:
      name: dicom-receiver-db-user
      usernameKey: username
      passwordKey: password
  bootstrapDatabase:
    enabled: false
    image: ghcr.io/zalando/spilo-17:4.0-p2
    databaseUserSecret:
      name: dicom-receiver-bootstrap-db-user
      usernameKey: username
      passwordKey: password

caCertsConfigMap:
  enabled: false
  name: "ca-certs"
  fileName: "ca-certificates.crt"
