apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "db.pvcName" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.requestedStorage | quote }}
