hostname: "example.com"

tls:
  enabled: false
  secretName: "tls-cert"

services:
  panel:
    enabled: true
    path: /panel
    name: fmx-panel

  fuego:
    enabled: true
    path: /fhir
    name: fuego

  grafana:
    enabled: true
    path: /grafana
    name: grafana

  keycloak:
    enabled: false
    path: /auth
    name: keycloak
