apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .Values.clusterName | default "pg" }}
spec:
  teamId: {{ .Values.teamId | default "main" | quote }}
  dockerImage: {{ .Values.image | quote }}
  numberOfInstances: {{ .Values.numberOfInstances | default 1 }}
  postgresql: {{ .Values.postgresql | toYaml | nindent 4 }}
  volume: {{ .Values.volume | toYaml | nindent 4 }}
  resources: {{ .Values.resources | toYaml | nindent 4 }}
  enableMasterLoadBalancer: {{ .Values.enableMasterLoadBalancer }}
  users:
    {{ .Values.username }}:
      - superuser
      - createdb
  databases:
    {{ .Values.databaseName }}: {{ .Values.username }}
  {{- with .Values.env }}
  env: {{ . | toYaml | nindent 5 }}
  {{- end }}
  {{- with .Values.allowedSourceRanges }}
  allowedSourceRanges: {{ . | toYaml | nindent 4 }}
  {{- end }}
  enableShmVolume: false
