apiVersion: v2
name: fmx-apps
description:
version: 0.1.0
dependencies:
  - name: keycloak
    version: 24.7.4
    repository: "https://charts.bitnami.com/bitnami"
    condition: provision.keycloak.enabled
