registryAuth:
  enabled: false
  server: "repo.firemetricshealth.com"
  username: ""
  password: ""

image: repo.firemetricshealth.com/ghcr/firemetrics/spilo16:3.3-p2-latest
numberOfInstances: 1
volume:
  size: 10Gi
resources:
  requests:
    cpu: "10m"
    memory: "100Mi"
  limits:
    cpu: "32"
    memory: "128Gi"

postgresql:
  version: "16"
  parameters:
    shared_buffers: 2GB
    max_locks_per_transaction: "512"
    work_mem: "256MB"

databaseName: firemetrics
username: firemetrics
