{{- $caCertsVolumeName := "ca-certs" -}}
{{- $caCertsPath := "/etc/ssl/certs/ca-certificates.crt" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{ include "appName" . }}
      app.kubernetes.io/component: frontend
      app.kubernetes.io/name: {{ include "podLabel" . }}
  template:
    metadata:
      name: {{ include "appName" . }}
      labels:
        app.kubernetes.io/part-of: {{ include "appName" . }}
        app.kubernetes.io/component: frontend
        app.kubernetes.io/name: {{ include "podLabel" . }}
    spec:
      {{- with .Values.serviceAccountName }}
      serviceAccountName: {{ . }}
      {{- end }}

      {{- with .Values.initContainers }}
      initContainers:
        {{- . | toYaml | nindent 8 }}
      {{- end }}

      {{- with .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}

      {{- if or .Values.caCertsConfigMap.enabled .Values.volumes }}
      volumes:
        - name: {{ $caCertsVolumeName | quote }}
          configMap:
            defaultMode: 0644
            name: {{ .Values.caCertsConfigMap.name | quote }}

        {{- with .Values.volumes }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
      {{- end }}

      containers:
        - name: main
          image: {{ .Values.image | quote }}
          ports:
            - name: http
              containerPort: 8000

          {{- with .Values.securityContext }}
          securityContext: {{- . | toYaml | nindent 12 }}
          {{- end }}

          {{- if or .Values.caCertsConfigMap.enabled .Values.volumeMounts }}
          volumeMounts:
            - name: {{ $caCertsVolumeName | quote }}
              mountPath: {{ $caCertsPath | quote }}
              readOnly: true
              subPath: {{ .Values.caCertsConfigMap.fileName | quote }}

            {{- with .Values.volumeMounts }}
              {{- . | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}

          env:
            - name: FMXPANEL_PUBLIC_PATH
              value: {{ .Values.publicPath | quote }}
            - name: FMXPANEL_DATABASE_HOST
              value: {{ .Values.database.hostname | quote }}
            - name: FMXPANEL_DATABASE_PORT
              value: {{ .Values.database.port | quote }}
            - name: FMXPANEL_DATABASE_NAME
              value: {{ .Values.database.dbname | quote }}
            - name: FMXPANEL_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.userSecret | quote }}
                  key: username
            - name: FMXPANEL_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.userSecret | quote }}
                  key: password
            - name: FMXPANEL_FHIR_BASE_URL
              value: {{ .Values.fhirBaseUrl | quote }}

            - name: FMXPANEL_FEATURE_FLAGS
              value: {{ .Values.featureFlags | join "," | quote }}

            {{- with .Values.grafanaUrl }}
            - name: FMXPANEL_GRAFANA_URL
              value: {{ . | quote }}
            {{- end }}

            {{- if .Values.openaiApiKeySecret.enabled }}
            - name: FMXPANEL_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.openaiApiKeySecret.name | quote }}
                  key: {{ .Values.openaiApiKeySecret.key | quote }}
            {{- end }}

            {{- if .Values.oidc.enabled }}
            - name: FMXPANEL_OIDC_ENABLED
              value: "true"
            - name: FMXPANEL_OIDC_DISCOVERY_URL
              value: {{ .Values.oidc.discoveryUrl | quote }}
            - name: FMXPANEL_OIDC_CLIENT_ID
              value: {{ .Values.oidc.clientId | quote }}
            - name: FMXPANEL_OIDC_AUDIENCE
              value: {{ include "oidcAudience" . | quote }}
            {{- end }}

            {{- if .Values.caCertsConfigMap.enabled }}
            - name: REQUESTS_CA_BUNDLE
              value: {{ $caCertsPath | quote }}
            - name: SSL_CERT_FILE
              value: {{ $caCertsPath | quote }}
            {{- end }}

            {{- with .Values.env }}
              {{- . | toYaml | nindent 12 }}
            {{- end }}
