apiVersion: v1
kind: Service
metadata:
  name: {{ include "svcName" . }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/part-of: {{ include "appName" . }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/name: {{ include "podLabel" . }}
