apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "childAppName" . }}
  namespace: {{ .Values.argoCdNamespace | quote }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: {{ .Values.application.chartRepoUrl | quote }}
    chart: tenant
    targetRevision: {{ .Values.application.chartVersion | quote }}
    helm:
      releaseName: {{ include "childAppName" . }}
      values: |
      {{- if .Values.application.valuesOverride }}
        {{- .Values.application.valuesOverride | toYaml | nindent 8 }}
      {{- else }}
        tenant:
          name: {{ include "tenantName" . | quote }}
          certificate:
            requestAutoCert: false
          configSecret:
            existingSecret: true
            name: {{ .Values.configSecretName | quote }}
          pools:
            - servers: {{ .Values.servers }}
              name: {{ .Values.poolName | quote }}
              volumesPerServer: {{ .Values.volumesPerServer }}
              size: {{ .Values.size }}
          {{- if or .Values.backup.enabled .Values.dicom.enabled }}
          buckets:
            {{- if .Values.backup.enabled }}
            - name: {{ .Values.backup.bucketName | quote }}
            {{- end }}
            {{- if .Values.dicom.enabled }}
            - name: {{ .Values.dicom.bucketName | quote }}
            {{- end }}
          {{- end }}
      {{- end }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}

  {{- with .Values.application.syncPolicy }}
  syncPolicy: {{- . | toYaml | nindent 4 }}
  {{- end }}
