apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "childAppName" . | quote }}
  namespace: {{ .Values.argoCdNamespace | quote }}
spec:
  project: default

  source:
    repoURL: {{ .Values.application.chartRepoUrl | quote }}
    chart: keycloak
    targetRevision: {{ .Values.application.chartVersion | quote }}
    helm:
      releaseName: {{ include "childAppName" . | quote }}
      values: |
      {{- if .Values.application.valuesOverride }}
        {{- .Values.application.valuesOverride | toYaml | nindent 8 }}
      {{- else }}
        production: true
        httpRelativePath: {{ .Values.publicPath }}/
        proxyHeaders: xforwarded
        extraStartupArgs: "--import-realm"
        externalDatabase:
          host: "none"
        {{- if or .Values.importRealm.enabled .Values.persistence.enabled }}
        extraVolumes:
          {{- if .Values.persistence.enabled }}
          - name: keycloak-data
            persistentVolumeClaim:
              claimName: {{ include "dataPvcName" . | quote }}
          {{- end }}
          {{- if .Values.importRealm.enabled }}
          - name: keycloak-import
            configMap:
              name: {{ include "importRealmConfigMapName" . | quote }}
          {{- end }}
        extraVolumeMounts:
          {{- if .Values.persistence.enabled }}
          - name: keycloak-data
            mountPath: /opt/bitnami/keycloak/data/h2
          {{- end }}
          {{- if .Values.importRealm.enabled }}
          - name: keycloak-import
            mountPath: /opt/bitnami/keycloak/data/import
          {{- end }}
        {{- end }}
        postgresql:
          enabled: false
        extraEnvVars:
          - name: KEYCLOAK_DATABASE_VENDOR
            value: "dev-file"
        externalDatabase:
          password: notused
      {{- end }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}

  {{- with .Values.application.syncPolicy }}
  syncPolicy: {{- . | toYaml | nindent 4 }}
  {{- end }}
