{{- if .Values.importRealm.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "importRealmConfigMapName" . }}
data:
  {{ .Values.importRealm.realmName }}-realm.json: |
    {
      "realm": "{{ .Values.importRealm.realmName }}",
      "enabled": true,
      "defaultDefaultClientScopes": ["basic"],
      "clients": [
        {
          "clientId": {{ .Values.panel.clientId | quote }},
          "enabled": true,
          "publicClient": true,
          "redirectUris": ["{{ .Values.panel.publicUrl }}/*"],
          "defaultClientScopes": [
            "basic",
            "attribute-fhir-user",
            "audience-panel",
            "audience-fuego"
          ]
        }
      ],
      "clientScopes": [
        {
          "name": "basic",
          "description": "OpenID Connect scope for add all basic claims to the token",
          "protocol": "openid-connect",
          "attributes": {
            "include.in.token.scope": "false",
            "display.on.consent.screen": "false"
          },
          "protocolMappers": [
            {
              "name": "auth_time",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usersessionmodel-note-mapper",
              "consentRequired": false,
              "config": {
                "user.session.note": "AUTH_TIME",
                "id.token.claim": "true",
                "introspection.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "auth_time",
                "jsonType.label": "long"
              }
            },
            {
              "name": "sub",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-sub-mapper",
              "consentRequired": false,
              "config": {
                "introspection.token.claim": "true",
                "access.token.claim": "true"
              }
            }
          ]
        },
        {
          "name": "attribute-fhir-user",
          "protocol": "openid-connect",
          "protocolMappers": [
            {
              "name": "attribute-mapper",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-attribute-mapper",
              "consentRequired": false,
              "config": {
                "aggregate.attrs": "false",
                "introspection.token.claim": "true",
                "userinfo.token.claim": "true",
                "user.attribute": "fhirUser",
                "access.token.claim": "true",
                "claim.name": "fhirUser",
                "jsonType.label": "String"
              }
            }
          ]
        },
        {
          "name": "audience-fuego",
          "protocol": "openid-connect",
          "protocolMappers": [
            {
              "name": "audience-mapper",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-mapper",
              "consentRequired": false,
              "config": {
                "included.custom.audience": {{ .Values.fuego.oidcAudience | quote }},
                "id.token.claim": "false",
                "access.token.claim": "true"
              }
            }
          ]
        },
        {
          "name": "audience-panel",
          "protocol": "openid-connect",
          "protocolMappers": [
            {
              "name": "audience-mapper",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-mapper",
              "consentRequired": false,
              "config": {
                "included.custom.audience": {{ .Values.panel.oidcAudience | quote }},
                "id.token.claim": "false",
                "access.token.claim": "true"
              }
            }
          ]
        }
      ]
    }
{{- end -}}
